### ISSUE TITLE
Wait for service to start?

### ISSUE THREAD

**Issue by alexandrosm** [meetfinch/decking#21]
[Maestro](https://github.com/toscanini/maestro) has this feature whereby it waits for containers to actually be ready to accept connections before starting to launch others that depend on them. The implementation for that is [here](https://github.com/toscanini/maestro/blob/master/maestro/utils.py#L70-L83). This feels like a feature decking should have, especially considering the strong support for links.

**Comment by makeusabrew** [comment]
Fixed in 0.4.0 :)
