### ISSUE TITLE
Multi-machine support ?

### ISSUE THREAD

**Issue by djsly** [meetfinch/decking#32]
Hi I read a lot about decking since I am looking for an orchestration tool for Docker. 

I can't seem to figure out if multi-machine cluster is something that is support bu the decking tool.

**Comment by raykrueger** [comment]
Just a note, I did get this working with Docker Swarm to support multiple machines :)

**Comment by makeusabrew** [comment]
Hi @raykrueger,

Thanks for the update. I'm curious and way behind the times with Docker's tooling; did you use `swarm` in tandem with `decking` or instead of it? Thanks!

**Comment by raykrueger** [comment]
I setup 3 docker nodes. I launched the swarm manager and added those 3 nodes to the swarm. Then you point decking at the swarm manager instance (as if it were the docker host basically).

**Comment by raykrueger** [comment]
(hit enter too early)
I used decking and swarm together :)

**Comment by makeusabrew** [comment]
Great; thank you very much - really interesting! Will have to give it a go myself and get some updates in the docs. Much appreciated :)
