### ISSUE TITLE
Specify custom Tags

### ISSUE THREAD

**Issue by robodude666** [meetfinch/decking#53]
Currently it seems all images are built with the tag "latest." It would be nice to be able to specify tags within the decking.json file, and even as command line overrides.

For example being able to tag a "dev" image separate from a "test" build without having to name the image differently. This would produce:
```
my-image:dev
my-image:test
```
vs
```
my-image-dev:latest
my-image-dev:test
```

Might even just produce the tag based on the cluster/group name?

The ability to override tags via command line could be used in a CI environment to name the tag after the SHA-1 hash of a git commit or a brand name, for example.

**Comment by makeusabrew** [comment]
Fixed in 0.4.0 with `--tag` parameter :)
