### ISSUE TITLE
ENOENT/socket hangup on Mac OSX + boot2docker

### ISSUE THREAD

**Issue by jraede** [meetfinch/decking#63]
On cluster start and restart (and I'm sure on most other commands), I get "connect ENOENT" and "socket hang up" errors. The containers started fine the first time but I am unable to stop them through decking (only docker itself). I'm assuming this is because I am running everything on Mac OSX + boot2docker and the IPs in decking are probably expected to be local. Is anyone else experiencing this?

**Comment by makeusabrew** [comment]
Just doing a bit of cleanup here and closing this one folks. This was fixed in v0.3.0 which was published some time ago :)
