### ISSUE TITLE
Groups override of containers still require explicit dependencies.

### ISSUE THREAD

**Issue by djalexd** [meetfinch/decking#80]
Hi @makeusabrew and thanks for this great tool! I've been kicking myself the last couple of days with it, mostly it works really well - but a couple of things could really be improved.

One of these things is as follows:

```
{
  "images": ...
  "containers": {
      "foo": { .... },
     "bar": {
        "dependencies: [ "foo" ]
      }
  },
  "clusters": {
    "foobar": {
      "containers": [ "foo", "bar" ]
    }
  },
  "groups": {
     "foobar": {
        "containers": {
           "bar": {  ... customize with others options like mount, port, 
                            BUT don't touch dependencies ...
           }
        }
    }
  }
}
```

Running "foobar" cluster will fail with not a lot of info available; the underlying problem is that there's this group override and "bar" container inside. However, if I add the same dependencies in group "foobar" / "containers" / "bar", it works properly. Is this expected?

I also saw a couple of other open issues related to merging arguments, options, etc. Possible duplicate or another issue? If you want, I can provide you with an example. I also haven't tried yaml format yet.

**Comment by makeusabrew** [comment]
Hi @djalexd,

Apologies; I've been on vacation for the past 3 weeks and have a rather large backlog of issues to get through. I'll try and look at this in detail and get back to you as soon as I can :).

Nick

**Comment by guillaumelecerf** [comment]
I think that it is related to options merging, see #78

**Comment by makeusabrew** [comment]
Hi @djalexd,

I think I stumbled upon this bug tonight albeit in a different form. I'll ping you when 0.4.0 is out (this Saturday); if you could retest at your own leisure afterwards that would be great :)

**Comment by makeusabrew** [comment]
0.4.0 now available; would appreciate any feedback on this :)
