### ISSUE TITLE
Support for container runtime constraints on CPU and memory

### ISSUE THREAD

**Issue by hrbu** [meetfinch/decking#83]
Is there an option to define runtime constraints within the container-definition?
----
see https://docs.docker.com/reference/run/#runtime-constraints-on-cpu-and-memory

**Comment by arahayrabedian** [comment]
@hrbu not sure if it'll meet your needs, but you can try the "extra" portion of the json definition: see [decking.io](http://decking.io/#format-containers) and find the definition of extra in there.

**Comment by hrbu** [comment]
@arahayrabedian saw this, but as i understand (and my test seemed to confirm it) those extra arguments are passed into the container to run a command there. so ... it did't meet my needs

**Comment by arahayrabedian** [comment]
ah, okay, i see what you mean now (sorry my interpretation was that extra string would append whatever cli extras you want, that is ambiguous as i re-read it now) and you suggest it runs some commands on startup, i'll leave this for someone else then.

**Comment by makeusabrew** [comment]
Will take a look at these; probably not for 0.4.0 but the next minor release after that.

**Comment by makeusabrew** [comment]
Done; look out for 0.4.0

**Comment by makeusabrew** [comment]
Fixed in 0.4.0

**Comment by hrbu** [comment]
Cool. Thanx a lot.
