### ISSUE TITLE
Is this project stale/dead?

### ISSUE THREAD

**Issue by blackbarn** [meetfinch/decking#93]
After reviewing docker-compose and decking I really like decking. However it looks like it hasn't seen much activity in a while. Anyone able to chime in on the matter?

**Comment by corbinu** [comment]
@blackbarn I will be issuing some pull requests in the coming week as I new features for lifecyle management. We will see how that goes. Was there anything in particular you wanted to see added?

**Comment by blackbarn** [comment]
Nothing in particular. I have one PR for supporting the restart option on run, but thats not critical. Was just curious if i spent any time contributing, would it be fruitless or not :)
